#!/bin/sh

port="$(uci -q get openvpn.myvpn.port)"
proto="$(uci -q get openvpn.myvpn.proto)"
wan_zone="$(
	uci show firewall |
		grep "\.name='wan'$" |
		cut -d. -f1-2 |
		head -n 1
)"

case "${port}" in
	''|*[!0-9]*)
		exit 0
		;;
esac

case "${proto}" in
	tcp4|tcp6)
	firewall_proto='tcp'
	;;
*)
	firewall_proto='udp'
	;;
esac

uci -q set firewall.openvpn.dest_port="${port}"
uci -q set firewall.openvpn.proto="${firewall_proto}"

# OpenVPN clients need standard source NAT to reach both the upstream private
# subnet and the Internet. Full-cone NAT does not reliably translate TCP flows
# from tun0 on this fw4 build.
uci -q set firewall.@defaults[0].fullcone='0'
if [ -n "${wan_zone}" ]; then
	uci -q set "${wan_zone}.masq=1"
	uci -q set "${wan_zone}.mtu_fix=1"
fi
uci -q commit firewall

exit 0
