#!/bin/sh

uci -q set network.lan.ipaddr='192.168.2.1'
uci -q delete network.lan.ip6assign

# Keep the device-specific suffix while avoiding an upstream clone of the
# factory WAN MAC, which breaks IPv4 return traffic and IPv6 DAD.
wan_device="$(
	uci show network |
		grep "\.name='wan'$" |
		cut -d. -f1-2 |
		head -n 1
)"
wan_mac="$(uci -q get "${wan_device}.macaddr")"
case "${wan_mac}" in
	??:??:??:??:??:??)
		uci -q set "${wan_device}.macaddr=02:${wan_mac#*:}"
		;;
esac

uci -q set network.wan6='interface'
uci -q set network.wan6.proto='dhcpv6'
uci -q set network.wan6.device='@wan'
uci -q set network.wan6.reqaddress='try'
uci -q set network.wan6.reqprefix='auto'
uci -q commit network

uci -q set dhcp.lan.ra='relay'
uci -q set dhcp.lan.dhcpv6='relay'
uci -q set dhcp.lan.ndp='relay'
uci -q delete dhcp.lan.ra_slaac
uci -q delete dhcp.lan.ra_management
uci -q set dhcp.wan.master='1'
uci -q set dhcp.wan.ra='relay'
uci -q set dhcp.wan.dhcpv6='relay'
uci -q set dhcp.wan.ndp='relay'
uci -q commit dhcp

uci -q del_list openvpn.myvpn.push='route 192.168.1.0 255.255.255.0'
uci -q add_list openvpn.myvpn.push='route 192.168.2.0 255.255.255.0'
uci -q commit openvpn

exit 0
